name: navigation_samples
description: Sample navigation code.
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.6.2

dev_dependencies:
  example_utils:
    path: ../../example_utils

flutter:
  uses-material-design: true
